### ISSUE TITLE
Installation via Package Control fails on Windows

### ISSUE THREAD

**Issue by alteredq** [WebGLTools/GL-Shader-Validator#4]
When you just follow the installation instructions and use Package Control for Sublime 2 on Windows, shader validation doesn't work.

I think a problem is that plugin Python source expects a location with `GL-Shader-Validator` folder name but files get installed into `GL Shader Validator` folder instead.

https://github.com/WebGLTools/GL-Shader-Validator/blob/master/GLShaderValidator.py#L34

I made it work somehow by hacking the source, though I think a proper solution should be to modify whatever thing it is that controls folder names in Package Control.

**Comment by paullewis** [comment]
Interesting, thanks for the heads up! I think that is a weird call by Package Control. I'll see if I can get that fixed ASAP.

**Comment by brendankenny** [comment]
Oh, that is interesting. That's that opposite problem from before Package Control :)

It's a poor solution, but we could just test for both...or at least until Package Control does its next pulls.

**Comment by paullewis** [comment]
OK, this should now be fixed. Apologies for that, it looks like Package Control uses the name in the listing for the directory name (which wasn't clear to me) - I've updated the Python and installation instructions.

@alteredq I don't know if you editing the Python file yourself will undermine any updates we push out, so you may want to delete and reinstall it via Package Control. If you _do_ do that can you let me know if it works? I'll leave this open until I've verified it works on Windows; it does on Mac.

**Comment by alteredq** [comment]
Ok, I just did the standard update via Package Control and it seems it managed to fix it just fine ;)

I think update just overwrote my file changes, what I see in Python source file are exactly the changes you committed.

BTW I don't know if this is coming from the same thing, but Sublime menu items are still broken (`Preferences => Package settings => GL Shader Validator => readme / license / menu`) - all three files are attempted to be open in non-existent `GL-Shader-Validator` folder instead of the real `GL Shader Validator` one.

**Comment by paullewis** [comment]
Yep that'll be all the same issue - also fixed. Thanks for testing it sir! :)
