### ISSUE TITLE
Add /* global var_name */ directive to tell validator variable is defined elsewhere

### ISSUE THREAD

**Issue by s9k** [WebGLTools/GL-Shader-Validator#8]

**Comment by brendankenny** [comment]
Can you add some more details to what you're proposing? This wouldn't work with just a jshint-style declaration like that, since the shader validator will also need to know if it's a varying, attribute, uniform, `const`, what its type is, etc. At some point you might as well just declare the variable.

Is this to allow composing shader code but still validate each part? It seems like it would be helpful to be able to declare functions as external in that case as well.

**Comment by s9k** [comment]
Thank you for your feedback!

I use ThreeJS framework. ThreeJS predefine (automatically add at the beginning) some uniforms and attributes:

``` glsl
uniform mat4 modelMatrix;
uniform mat4 modelViewMatrix;
uniform mat4 projectionMatrix;
uniform mat4 viewMatrix;
uniform mat3 normalMatrix;
uniform vec3 cameraPosition;

attribute vec3 position;
attribute vec3 normal;
attribute vec2 uv;
attribute vec2 uv2;
```

So I get 'undeclared identifier' validator warning when use some of them in my shader code.

**Comment by brendankenny** [comment]
Ah, got it. This would be nice to fix. I believe evanw's [lightgl.js](https://github.com/evanw/lightgl.js) also includes a bunch of default uniforms and attributes, too.

So, one option is the jshint-style approach, allowing these to be defined as mentioned above with some kind of `/* global ... */` syntax. The validator would then prepend those to the file before passing it to ANGLE. Like jshint in Sublime, you could also include globals for all files in the User Package Settings; that way people who only develop three.js shaders, for instance, would have those globals for all their shaders by default.

I wonder if there is a more shader-idiomatic solution, though, some kind of `#ifdef`chicanery or some kind of `#include` macro like in [glsl-unit](https://code.google.com/p/glsl-unit/). You could include other shaders by filename (the validator would just concatenate them), and the validator could ship with some defaults, so `#include threejs` or whatever would take care of the issue (and, as above, you could put some defaults in the Package Settings so you wouldn't have to write it every time).

I'm leaving tomorrow on a trip, so won't be able to look at this for a few weeks (away from internet access for a good chunk of it), but feel free to weigh in on possible solutions in the meantime, as can anyone else who happens to read this.

**Comment by flcoder** [comment]
Ha, this is great, I was just having the same issue.  I would love having validation inside sublime, but I also use threejs and need to specify globals.  Will check into a #ifndef or something for the time being.
